Handler for invalid JSON response from Linkedin [WIP]
hasgeek/funnel pull request #1011
Opened 2021-01-25 05:02 UTC by iambibhas

LinkedIn sent HTML back to a JSON endpoint with a 502 Server Hangup response. We need to handle that exception and not throw 500 to the user.

Needs to be added to this PR: Translations. Another PR has translation updates from master. Need to close that first to update translations on this branch.

2021-01-25 05:03 UTC, iambibhas commented on funnel/loginproviders/linkedin.py
> +    token_url = 'https://www.linkedin.com/uas/oauth2/accessToken'  # nosec
Bandit detected this line as low severity hardcoded password for some reason. Had to add `# nosec`.

2021-01-25 05:33 UTC, jace requested changes

2021-01-25 05:33 UTC, jace commented on funnel/loginproviders/linkedin.py
> +                _("Invalid response from LinkedIn: {error}").format(error=e)
This is shown to the user, so it should be user friendly.

2021-01-27 10:47 UTC, jace approved these changes

2021-01-27 13:49 UTC, merged