Change project into a spa
hasgeek/funnel pull request #1299
Opened 2021-12-01 12:55 UTC by vidya-ram

2021-12-10 04:38 UTC, jace requested changes
The render_with calls can be simpler. Some other questions.

2021-12-10 04:38 UTC, jace commented on funnel/views/membership.py
> +            )
This should be given to `render_with`. It can be told to render for different targets.

2021-12-10 04:38 UTC, jace commented on funnel/views/project.py
> +            )
Same here

2021-12-10 04:55 UTC, vidya-ram commented on funnel/assets/js/schedule_view.js
> +          stateData = {
Initially, there was two different assignments so declared it this. Can be removed now.

2021-12-13 06:54 UTC, jace commented on funnel/views/helpers.py
> +    return {'text/html': template, 'application/json': render_html_in_json, 'x.html+json': template}
This should be:
```python
{
	'text/html': template,
	'application/json': jsonify,
	'application/x.html+json': render_html_in_json,
}
```

2021-12-19 18:33 UTC, jace reviewed
Some backend changes required to avoid recursion errors in pure JSON responses.

2021-12-19 18:33 UTC, jace commented on funnel/views/membership.py
> +        self.obj
This line can be removed

2021-12-19 18:33 UTC, jace commented on funnel/views/project.py
> +                _p.current_access()
Needs `datasets=('without_parent', 'related')` (assuming Proposal model defines a 'without_parent' dataset, which it should).

2021-12-19 18:33 UTC, jace commented on funnel/views/project.py
> +            'submissions': self.obj.proposals,
Needs `current_access`. Also needs consistency between 'proposal' and 'submission'. We are still using the term 'proposal' in all internal references, but we should switch over as a planned move.

2021-12-19 18:33 UTC, jace commented on funnel/views/project.py
>              'project': self.obj.current_access(),
Needs `datasets=('primary', 'related')`

2021-12-19 18:33 UTC, jace commented on funnel/views/project.py
> +            'project': self.obj.current_access(),
Needs `datasets=('primary', 'related')`

2021-12-19 18:33 UTC, jace commented on funnel/views/project.py
> +            'project': self.obj.current_access(),
Needs `datasets=('primary', 'related')`

2021-12-19 18:33 UTC, jace commented on funnel/views/project.py
> +            'project': self.obj.current_access(),
Needs `datasets=('primary', 'related')`

2021-12-19 18:33 UTC, jace commented on funnel/views/project.py
>              'going_rsvps': self.obj.rsvps_with(RSVP_STATUS.YES),
Needs `'going_rsvps': [_r.current_access(datasets=('without_parent', 'related')) for _r in self.obj.rsvps_with(RSVP_STATUS.YES)],`

2021-12-19 18:33 UTC, jace commented on funnel/views/project.py
> +        project = self.obj.current_access()
Needs `datasets=('primary', 'related')`

2021-12-19 18:33 UTC, jace commented on funnel/views/update.py
>                  update.current_access(datasets=('primary', 'related'))
Here instead of `primary` dataset it should be `without_parent`, as primary will include the project's data with each update.

2021-12-19 18:33 UTC, jace commented on funnel/views/update.py
> +            update.current_access(datasets=('primary', 'related'))
Again `without_parent` instead of `primary`

2021-12-20 09:18 UTC, jace requested changes

2021-12-20 09:18 UTC, jace commented on funnel/views/project.py
> +            'submissions': self.obj.proposals.current_access(datasets=('primary', 'related')),
`without_parent` here

2021-12-20 09:18 UTC, jace commented on funnel/views/project.py
> +            'project': self.obj.current_access(datasets=('primary', 'related')),
`without_parent` since the parent is passed separately as the `profile`.

2021-12-20 09:18 UTC, jace commented on funnel/views/project.py
> +            'profile': self.obj.profile.current_access(datasets=('primary', 'related')),
This should be just `datasets=('primary',)` (note extra comma) without `related` as we don’t want to include other projects.

2021-12-20 09:18 UTC, jace commented on funnel/views/schedule.py
> +        return {'status': 'ok'}
The view needs `@render_with(json=True)`

2021-12-20 18:11 UTC, merged