Markdown parser using markdown-it-py
hasgeek/funnel pull request #1455
Opened 2022-08-23 18:34 UTC by miteshashar

2022-08-24 20:22 UTC, jace requested changes

2022-08-24 20:22 UTC, jace commented on funnel/utils/__init__.py
> +from .markdown import markdown
Always do `import *` in `__init__.py`, and declare an `__all__` list in the respective modules if you don't want to export everything.

2022-08-24 20:22 UTC, jace commented on funnel/utils/markdown/__init__.py
> +from .base import markdown
Same here, `import *`

2022-08-24 20:22 UTC, jace commented on funnel/utils/markdown/base.py
> +class MarkdownItPluginProtocol(Protocol):  # pylint: disable=too-few-public-methods
This disable should not be necessary as it's already in the global list in `pyproject.toml`.

2022-08-24 20:22 UTC, jace commented on funnel/utils/markdown/base.py
> +default_markdown_extensions_html: Mapping[str, Type[MarkdownItPluginProtocol]] = {
The `Type[]` wrapper should not be necessary. You can use `Dict[str, MarkdownItPluginProtocol]` as this is an explicit dict and not an abstract Mapping.

2022-09-19 14:38 UTC, miteshashar reviewed
Need resolution on this to continue merging.

2022-09-19 15:58 UTC, merged