Add Codemirror 6 to submission form
hasgeek/funnel pull request #1510
Opened 2022-11-03 06:22 UTC by vidya-ram

2022-11-07 09:29 UTC, miteshashar commented
Submission form views when there are no labels created for the project.

*New Submission*
<img width="974" alt="image" src="https://user-images.githubusercontent.com/1172235/200274686-65e36563-3eae-4368-9562-87ef7bacfcc2.png">

*Edit Submission*
<img width="965" alt="image" src="https://user-images.githubusercontent.com/1172235/200274978-d4b3be6c-ef85-42e0-a25c-088344b00811.png">

The placement of the 3 possible fields here should be handled such that they are aesthetically placed in the UI.

1 field: Left
2 fields: Left, Right
3 fields: Left, Center, Right

2022-11-07 09:34 UTC, miteshashar commented
There is no way to go back from the Add Collaborator popup. The only way is reloading the page, which would mean all unsaved changes are lost.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/1172235/200276462-b0834c61-cf93-4bbc-9bee-3a633852eb28.png">

2022-11-07 10:25 UTC, vidya-ram commented
> Submission form views when there are no labels created for the project.
> 
> **New Submission** <img alt="image" width="974" src="https://user-images.githubusercontent.com/1172235/200274686-65e36563-3eae-4368-9562-87ef7bacfcc2.png">
> 
> **Edit Submission** <img alt="image" width="965" src="https://user-images.githubusercontent.com/1172235/200274978-d4b3be6c-ef85-42e0-a25c-088344b00811.png">
> 
> The placement of the 3 possible fields here should be handled such that they are aesthetically placed in the UI.
> 
> 1 field: Left 2 fields: Left, Right 3 fields: Left, Center, Right

Fixed

2022-11-07 10:25 UTC, vidya-ram commented
> There is no way to go back from the Add Collaborator popup, in case one does not want to add one. <img alt="image" width="523" src="https://user-images.githubusercontent.com/1172235/200276462-b0834c61-cf93-4bbc-9bee-3a633852eb28.png"> The only way is reloading the page, which would mean all unsaved changes are lost.
> 
> Moreover, the user dropdown does not load any values. <img alt="image" width="516" src="https://user-images.githubusercontent.com/1172235/200278837-33ec961a-2e78-4466-8f98-59c972e07b09.png">
> 
> Clicking 'Add Collaborator' goes to the API url(losing all changes made to content). On the new page, the user field renders as an autocomplete field, though in the modal, it renders as a dropdown. <img alt="image" width="965" src="https://user-images.githubusercontent.com/1172235/200278549-2e7dab6b-5b16-40ed-a5a4-a7fa32a6556d.png">
> 
> Submitting this form successfully gets processed, but replaces the full page with JSON. <img alt="image" width="1099" src="https://user-images.githubusercontent.com/1172235/200278352-6e7a0537-db2c-4525-8b86-3aa603249c0e.png">

Fixed

2022-11-07 10:53 UTC, miteshashar commented
Submitting blank form shows a toastr message with text "parsererror".

<img width="815" alt="image" src="https://user-images.githubusercontent.com/1172235/200292902-75f9ab7d-0abd-4eba-b7ac-4b00eb7fe28b.png">

2022-11-10 05:58 UTC, vidya-ram commented
> Submitting blank form shows a toastr message with text "parsererror".
> 
> <img alt="image" width="815" src="https://user-images.githubusercontent.com/1172235/200292902-75f9ab7d-0abd-4eba-b7ac-4b00eb7fe28b.png">

Fixed

2022-11-15 06:55 UTC, jace requested changes
One redundant `if` statement in the Python code.

2022-11-15 06:55 UTC, jace commented on funnel/static/js/scripts.js
> +    document.querySelector('.select2-search__field').focus();
Will this work if the page has multiple select2 widgets?

2022-11-15 06:55 UTC, jace commented on funnel/views/proposal.py
> +            if collaborator_form.validate_on_submit():
`form.validate_on_submit()` is shorthand for `request.method == 'POST' and form.validate()` so the first `if` statement is not required.

2022-11-22 04:57 UTC, merged