Markdown preview fix
hasgeek/funnel pull request #1520
Opened 2022-11-15 09:11 UTC by djamg

Reverted back to old markdown utils in the API

2022-11-15 09:29 UTC, miteshashar approved these changes
Checked by running the same diff I shared earlier, looks good.
P.S. I did not run & test it.

2022-11-15 16:42 UTC, vidya-ram approved these changes

2022-11-21 09:11 UTC, jace requested changes

2022-11-21 09:13 UTC, jace approved these changes

2022-11-21 09:14 UTC, merged