Fix otp login modal on project page
hasgeek/funnel pull request #1597
Opened 2023-01-23 09:00 UTC by vidya-ram

2023-01-25 05:43 UTC, jace reviewed
One small optimisation.

Does Recaptcha work if the handling of RecaptchaField is removed?

2023-01-25 05:43 UTC, jace commented on funnel/templates/password_login_form.html.jinja2
> +        action="{{ url_for('login', next=request.path) }}%23register-modal">
You can specify `_anchor='register-modal'` as a parameter to `url_for`.

2023-01-25 05:51 UTC, vidya-ram commented
> One small optimisation.
> 
> Does Recaptcha work if the handling of RecaptchaField is removed?

This was the old and redundant one. We had newly introduced this as part of OTP
https://github.com/hasgeek/funnel/blob/main/funnel/templates/forms.html.jinja2#L214

2023-01-25 09:10 UTC, jace requested changes

2023-01-25 09:10 UTC, jace commented on funnel/templates/otpform.html.jinja2
> +  <form data-parsley-validate="true" id="{{ ref_id }}" method="post" hx-post="{{ url_for('login', next=request.path) }}%23register-modal" {%- if action %} action="{{ url_for('login', next=request.pat
OTP form is also used for `sudo`, where it does not redirect to login. This one should not hardcode login URL.

2023-02-01 06:01 UTC, jace commented on funnel/views/login.py
> +    action_url = url_for('login', next=next_url)
This line should be in the `else:` branch.

2023-02-01 06:35 UTC, merged