Added urlname to the callerid API
hasgeek/funnel pull request #1906
Opened 2023-10-18 18:39 UTC by djamg

2023-10-19 05:25 UTC, jace requested changes

2023-10-19 05:25 UTC, jace commented on funnel/views/api/support.py
> +            'urlname': user_phone.account.urlname,
Return `'url': user_phone.account.profile_url`

2023-10-20 06:13 UTC, jace approved these changes
Please confirm account.profile_url returns a URL regardless of the account state. If so, this is good to merge.

2023-10-20 09:28 UTC, jace submitted a review, later dismissed

2023-10-25 06:43 UTC, jace approved these changes

2023-10-25 07:44 UTC, vidya-ram approved these changes

2023-10-25 10:18 UTC, merged