Copying proposal if the existing proposal already has a session
hasgeek/funnel pull request #226
Opened 2018-04-02 10:20 UTC by iambibhas

2018-04-23 16:49 UTC, jace requested changes

2018-04-23 16:49 UTC, jace commented on funnel/views/proposal.py
> +                proposal = proposal.current_access().copy_to(target_space)
This has to be in the UI as well: don't show "Move to" if you can only make a copy.

2018-04-23 16:51 UTC, jace commented
@iambibhas When you make a copy, "user" must be the person who made the copy. "speaker" can remain as at present. We have to record the person who requested the copy operation.

2018-11-19 08:35 UTC, jace commented
Can you clean this up for merger?

2018-11-22 18:51 UTC, iambibhas commented
Pushed some fixes. But UI has some serious issue. /cc @vidya-ram 
![funnel-issue](https://user-images.githubusercontent.com/357253/48918913-a9cbd800-eeb5-11e8-9e8c-afa8f6ed1c4f.gif)

2018-12-12 10:07 UTC, jace commented
What should we do with this?

2018-12-12 10:08 UTC, jace commented
As per #327, proposals are no longer attached to projects. There is a separate `ProposalSubmission` instead.

2019-02-06 12:34 UTC, jace commented
@iambibhas this is the issue that broke for Zainab last week. Let's close this?

2019-10-25 09:19 UTC, jace requested changes
This has a few issues.

2022-05-16 15:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hasgeek/funnel?pullRequest=226) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hasgeek/funnel?pullRequest=226) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hasgeek/funnel?pullRequest=226) it.</sub>

2023-03-14 19:36 UTC, jace commented
This is now severely out of date, so we'll have to redo this as a new PR.

2023-03-14 19:36 UTC, closed without merging